sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-relay
before_install:
- pip install --user awscli
script: make
deploy:
  provider: script
  script: make release && aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
