sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-relay
  - secure: Mp68uYe4eofWppYyyMJLWHnYcQtMZvpqRrPtQkGeoOnacr+g2qyxL2di1BS/dlmVQe8WooOsiAkPKWTUCeqFMFnRtdj2YE2u0DhvrmMCZ24G5Wkej4BopJbdEIC0u0/lLA7Wj2PoK+ENnB4VNaa38AnFFtkfztaxZ4aSc4dBjKbLdZ4QhH/YD9A/HTCOJ4vGwiLkBgcZpxJ3QZMpu7QQ3RFb5jDNy2TmUfdamaj5HLaqZQsRUp2OuMWlSoBghRHliTldDm5uSLxWr1k/oW+ZU4nLBF+ANJoZHP1dqw4ZWsIxE7t/x9wqlu0nBQV8C2/r4QH8SA8W5PPhaBj4GS9+cBtNoNRb8I6zsR0x8bOFpc28VJD/bTc1s+0En0/oQXKtJOuOOGHep/zJelN3oO+CnVf2+UFNkhilByi/gG0qT160r3VHAOCtH5v/1jRZwhTRwL2kna2G+4rGb3/gkpDFhCLxyktsDaeex3J9oY5CBKg7fHna1E5j2sLUbAdHQ9LWwK8iJPz3ekZouLU9254ABiknnk8LxUQLBa5GgBaQZCTwxAp++MvNapdOptCP1xQCcTdpFYTxWU/b1FHCRJ0DAZ6MCaq+Z8vR3dPDp7zRbgxtllSKpSux1SZwROqf00IsrcLiv8cOsKc/5oka4CM+joFPp41QRI6yc2G+ac1YArY=
before_install:
- pip install --user awscli
script: make
deploy:
  provider: script
  script: make release && aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: H22AQ7nSFoi6cO6xd4tftS2acKMAWzD75HWxhKSi4o77NZVbH7174MaAfgRKc0ZuhaiDo3EIisS6pym0ifPVlzle6e3k6gRLCBQdASLO9gZl6CDMV1ICIJa131bQyoVT3cKJxZA4JLi9lYuZLwYT1w3WEZ0nAYA8Be/y+UQzLzmIrbYHkmFtN6MYzn4TLJehW+fPmkspozk4sv2vuDA85t3S6YW7PxLFKDwxz5xvEFp+klZRDhif3iViD5GEhfhhPvAsxiu9Z7puOS0HyAeNI82OI8vTRA6HaBmlshTdc572vD8RnbpukIuQOeyO70ppoSVUZhyJWG4VvImikCvNa3yFLBltGTPCq/oaLufD2Z9bHKhU2fDR1fPBQKsWlqib9sbuig0numDRsd3EUTvXFruZY5G2FDNBpASvUvnW0UWlFt+LeTEofykh/QEHGWjnGsDMPSjoHJq5WWHg2oBAQF+SCpLSTHSWkEYuCKQto4cb1GEXHcFsC8aryhnZZQnflO9r88pHvOhrZ+m4LRqOnpS7UTwnhwL6iyYle63fw744zxvQwVloLYqIhBFmvMDaU6EYlJs0KNySJ4P+tui5lKZ1/ajkU30JzxrEdtW6mhfqKZ29GZLmLnUcCF23xsOCd0eZLvPCjYJwUMxt+WWF624Ggay0XbMA1yVX7kOoT+M=
